#!/bin/sh
set -e
if [ "$1" = remove ] || [ "$1" = deconfigure ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl stop harmony.service || true
        systemctl disable harmony.service || true
    fi
fi
exit 0
